#!/usr/bin/env node
/**
 * Regenerates the marketing gallery (sales/assets/gallery/*.svg).
 * Every tile is REAL output of the shipped Cloud visual engine
 * (cloud/api/_lib/visuals.js) — not a mockup — so the homepage can honestly
 * say "generated by BrandForge". Headlines come from the brief (as they do in
 * production: the copy stage supplies them); benefits stay in their own
 * lanes so the composition reads like a real ad, not a repeated list.
 *
 *   node scripts/make_gallery.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bannerSvg } from '../cloud/api/_lib/visuals.js';

const out = join(dirname(fileURLToPath(import.meta.url)), '../sales/assets/gallery');
mkdirSync(out, { recursive: true });

const tiles = [
  ['coffee',   { product: 'Northline Coffee', audience: 'busy professionals', primary: '#E8B54A', secondary: '#0F172A',
    headline: 'First sip, better morning',
    subheadline: 'Roasted the same night it ships — times vary by area.',
    offer: 'Free delivery this week', cta: 'Explore the coffee',
    benefits: ['Fresh-roasted single origin', 'Same-day delivery', 'Traceable farms'] }],
  ['fitness',  { product: 'Forge Fitness', audience: 'early-morning lifters', primary: '#34D399', secondary: '#0B1220',
    headline: 'Your 6 AM has a coach',
    subheadline: 'Small classes, real programming, no mirrors posing.',
    offer: 'First week free', cta: 'Book a session',
    benefits: ['Coached strength plans', 'Small classes', 'First week free'], width: 1080, height: 1080 }],
  ['saas',     { product: 'Ledgerline', audience: 'finance teams', primary: '#818CF8', secondary: '#111528',
    headline: 'Close the books 3× faster',
    subheadline: 'Your team finishes the month before it ends.',
    cta: 'Start free trial',
    benefits: ['Close books 3× faster', 'Audit-ready exports', 'No per-seat surprise'] }],
  ['realty',   { product: 'Marble & Vine', audience: 'first-time buyers', primary: '#B4541E', secondary: '#F6F1E7',
    headline: 'Homes that show their papers',
    subheadline: 'Every listing verified before you ever visit.',
    cta: 'View homes',
    benefits: ['Verified listings only', 'Move-in ready homes', 'First-buyer guide included'] }],
  ['urdu',     { product: 'ایپکس کافی', audience: 'شہری پیشہ ور افراد', primary: '#E8B54A', secondary: '#1A1033',
    headline: 'صبح کی پہلی چائے، اپنے ٹائم پر',
    subheadline: 'آرڈر کریں اور دروازے پر پائیں — کوئی قطار نہیں۔',
    offer: 'پہلے آرڈر پر مفت ڈیلیوری', cta: 'ابھی دیکھیں',
    benefits: ['تازہ بھُنی ہوئی پھلیاں', 'اسی دن ڈیلیوری', 'ہر بیگ کھیت تک قابلِ تسکین'] }],
  ['story',    { product: 'Bloom Skincare', audience: 'sensitive skin', primary: '#F472B6', secondary: '#181520',
    headline: 'Skin first. Always.',
    subheadline: 'Fragrance-free formulas reviewed by dermatologists.',
    cta: 'Shop the set', width: 1080, height: 1920,
    benefits: ['Dermatologist reviewed', 'Fragrance free', 'Cruelty free'] }],
  // Homepage "same brief, two engines" tile — copy matches the AI-scene
  // tile (ai-karak.jpg) so the comparison is honestly the same brief.
  ['bold-vector-karak', { product: 'Karak Theory', audience: "Karachi's morning commuters", primary: '#E8B54A', secondary: '#0F172A',
    headline: "Karachi's mornings start with karak", subheadline: 'Brewed to order, delivered hot — no queue, no compromises.',
    benefits: ['Skip the 45-minute queue for a simple cup of karak', 'Real milk, real tea leaves, brewed to order', 'Delivered hot in under 15 minutes'], cta: 'Order Now' }],
];
// The "before" tile shows the pre-redesign calm composition (honest comparison).
const before = { product: 'Karak Theory', primary: '#E8B54A', secondary: '#0F172A',
  headline: "Karachi's mornings start with karak", subheadline: 'Brewed to order, delivered hot.',
  benefits: ['Skip the queue', 'Brewed to order', 'Delivered in 15 minutes'], cta: 'Order Now' };

for (const [name, cfg] of tiles) {
  const svg = bannerSvg({ watermark: false, width: 1200, height: 630, style: 'bold', ...cfg });
  writeFileSync(join(out, `${name}.svg`), svg);
  console.log('gallery tile:', name, `${cfg.width ?? 1200}x${cfg.height ?? 630}`);
}
writeFileSync(join(out, 'before-vector-karak.svg'), bannerSvg({ watermark: false, width: 1200, height: 630, style: 'essential', ...before }));
console.log('gallery tile: before-vector-karak (essential baseline)');
console.log('Done — real engine output in sales/assets/gallery/');
