import {validatePortable,portableBytes,PORTABLE_NOTICE} from '/portable-pack.js';
const $=id=>document.getElementById(id),desktop=document.querySelector('meta[name="transfer-platform"]').content==='desktop';
let headers={},pack=null,requestId=null,epoch=0;
$('notice').textContent=PORTABLE_NOTICE;
function saveFile(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function api(path='',method='GET',body){const r=await fetch('/api/transfers'+path,{method,headers:{...headers,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok)throw new Error(d.error||d.detail||'Archive operation failed');return d;}
function show(p){pack=p;requestId=crypto.randomUUID();$('consent').checked=false;$('inspection').hidden=false;$('name').textContent=p.name+' · from '+p.origin+(p.omitted_files?.length?' · PARTIAL CORE ARCHIVE':'');$('sections').replaceChildren();for(const k of ['strategy','copy','seo']){const h=document.createElement('h3'),t=document.createElement('pre');h.textContent=k;t.textContent=p.sections[k];$('sections').append(h,t);}$('files').replaceChildren();for(const omitted of p.omitted_files||[]){const li=document.createElement('li');li.textContent='NOT INCLUDED: '+omitted.name+' — '+omitted.reason;$('files').append(li);}for(const file of p.files){const li=document.createElement('li'),b=document.createElement('button');b.textContent=file.name+' · '+file.bytes+' bytes';b.onclick=()=>saveFile(new Blob([portableBytes(file)],{type:'application/octet-stream'}),file.name);li.append(b);$('files').append(li);}}
async function list(){const d=await api();$('archives').replaceChildren();for(const row of d.archives){const article=document.createElement('article'),open=document.createElement('button'),del=document.createElement('button');open.textContent='Open '+row.name;open.onclick=async()=>{const seq=++epoch;try{const d=await api('?id='+encodeURIComponent(row.id));const p=await validatePortable(d.pack);if(seq===epoch)show(p);}catch(e){$('message').textContent=e.message;}};del.textContent='Delete '+row.name;del.onclick=async()=>{if(!confirm('Delete this archive? Downloaded copies are not recalled.'))return;try{await api('?id='+encodeURIComponent(row.id),'DELETE');await list();}catch(e){$('message').textContent=e.message;}};article.append(open,del);$('archives').append(article);}}
$('file').onchange=async()=>{const seq=++epoch;pack=null;$('inspection').hidden=true;try{const file=$('file').files?.[0];if(!file)return;if(file.size>3000000)throw new Error('Choose a portable JSON file up to 3 MB.');const p=await validatePortable(JSON.parse(await file.text()));if(seq!==epoch)return;show(p);$('message').textContent='Checksums passed. Nothing uploaded. Review the content before saving.';}catch(e){$('message').textContent=e.message;}};
$('save').onclick=async()=>{const b=$('save');b.disabled=true;try{if(!pack||!$('consent').checked)throw new Error('Confirm permission to store this archive.');await api('','POST',{pack,request_id:requestId,consent:true});$('message').textContent='Archive saved. No generation, campaign allowance or approval state was imported.';await list();}catch(e){$('message').textContent=e.message;}finally{b.disabled=false;}};
$('export').onclick=()=>{if(pack)saveFile(new Blob([JSON.stringify(pack)],{type:'application/json'}),'brandforge-portable.json');};$('refresh').onclick=()=>list().catch(e=>$('message').textContent=e.message);
try{
 if(desktop){const r=await fetch('/api/session',{cache:'no-store'});if(!r.ok)throw new Error('Local session unavailable');const d=await r.json();headers={'X-BrandForge-Token':d.capability};}
 else{const r=await fetch('/api/config',{cache:'no-store'});if(!r.ok)throw new Error('Cloud configuration unavailable');const c=await r.json();const {createClient}=await import('/vendor/supabase.mjs');const sb=createClient(c.supabaseUrl,c.supabaseAnonKey);const d=await sb.auth.getSession();if(!d.data.session)throw new Error('Sign in through the workspace, then return here. Local inspection and export still work.');headers={Authorization:'Bearer '+d.data.session.access_token};}
 await list();$('message').textContent='Ready. Imports remain separate from native campaigns.';
}catch(e){$('message').textContent=e.message;}
