#!/usr/bin/env node
/**
 * Regenerates the marketing gallery (sales/assets/gallery/*.svg).
 * Every tile is REAL output of the shipped Cloud visual engine
 * (cloud/api/_lib/visuals.js) — not a mockup — so the homepage can honestly
 * say "generated by BrandForge".
 *
 *   node scripts/make_gallery.mjs
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bannerSvg } from '../cloud/api/_lib/visuals.js';

const out = join(dirname(fileURLToPath(import.meta.url)), '../sales/assets/gallery');
mkdirSync(out, { recursive: true });

const tiles = [
  ['coffee',   { product: 'Northline Coffee', audience: 'busy professionals', primary: '#E8B54A', secondary: '#0F172A', benefits: ['Fresh-roasted single origin', 'Same-day delivery', 'Traceable farms'], cta: 'Explore the coffee' }],
  ['fitness',  { product: 'Forge Fitness',    audience: 'early-morning lifters', primary: '#34D399', secondary: '#0B1220', benefits: ['Coached strength plans', 'Small classes', 'First week free'], cta: 'Book a session' }],
  ['saas',     { product: 'Ledgerline',       audience: 'finance teams', primary: '#818CF8', secondary: '#111528', benefits: ['Close books 3× faster', 'Audit-ready exports'], cta: 'Start free trial' }],
  ['realty',   { product: 'Marble & Vine',    audience: 'first-time buyers', primary: '#B4541E', secondary: '#F6F1E7', benefits: ['Verified listings only', 'Move-in ready homes'], cta: 'View homes' }],
  ['urdu',     { product: 'ایپکس کافی',        audience: 'شہری پیشہ ور افراد', primary: '#E8B54A', secondary: '#1A1033', benefits: ['تازہ بھُنی ہوئی پھلیاں', 'اسی دن ڈیلیوری'], cta: 'ابھی دیکھیں' }],
  ['story',    { product: 'Bloom Skincare',   audience: 'sensitive skin', primary: '#F472B6', secondary: '#181520', benefits: ['Dermatologist reviewed', 'Fragrance free'], cta: 'Shop the set', width: 1080, height: 1920 }],
];
for (const [name, cfg] of tiles) {
  const svg = bannerSvg({ watermark: false, width: 1200, height: 630, ...cfg });
  writeFileSync(join(out, `${name}.svg`), svg);
  console.log('gallery tile:', name, `${cfg.width ?? 1200}x${cfg.height ?? 630}`);
}
console.log('Done — real engine output in sales/assets/gallery/');
