"""Generate shared semantic tokens; client banner palettes are deliberately separate."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def render():
    data = json.loads((ROOT/'shared/design-tokens.json').read_text())
    css = '/* GENERATED by scripts/sync_design_tokens.py; not campaign branding. */\n'
    for selector, theme in [(':root', 'dark'), ('[data-theme="light"]', 'light')]:
        css += selector+'{'+''.join(f'--bf-{k}:{v};' for k, v in data[theme].items())
        css += ''.join(f'--bf-space-{k}:{v};' for k, v in data['space'].items())
        css += ''.join(f'--bf-radius-{k}:{v};' for k,v in data['radii'].items())
        css += f"--bf-radius:{data['radius']};--bf-font-ui:{data['font_ui']};--bf-font-display:{data['font_display']};"
        for alias, token in [('bg','bg'), ('card','card'), ('ink','ink'), ('mut','muted'), ('line','line'), ('bad','error'), ('good','success'), ('gold','accent'), ('gold-text','accent'), ('gold-ink','accent_ink'), ('inset','inset'), ('faint','faint'), ('paper','bg'), ('focus','focus')]:
            css += f'--{alias}:var(--bf-{token});'
        for alias, token in [('bg','bg'), ('card','card'), ('ink','ink'), ('muted','muted'), ('line','line'), ('gold','accent'), ('inset','inset'), ('faint','faint')]:
            value = data[theme][token].lstrip('#'); rgb = ' '.join(str(int(value[i:i+2],16)) for i in (0,2,4))
            css += f'--sb-{alias}-rgb:{rgb};--{"mut" if alias=="muted" else alias}-rgb:{rgb};'
            if alias=='ink': css += f'--sb-ink:{rgb};'
        css += '--sb-faint:var(--bf-faint);--sb-hairline:var(--bf-line);'
        css += '}\n'
    css += ':focus-visible{outline:3px solid var(--bf-focus)!important;outline-offset:3px}\n[aria-invalid="true"]{border-color:var(--bf-error)}\n.bf-error{color:var(--bf-error)}.bf-success{color:var(--bf-success)}\n'
    css += 'input:not([type=checkbox]):not([type=radio]),textarea,select{border-color:var(--bf-control_line)}input[aria-invalid="true"],textarea[aria-invalid="true"],select[aria-invalid="true"]{border-color:var(--bf-error)}\n'
    css += '.err,.bf-error{color:var(--bf-error);background:var(--bf-card);border-color:var(--bf-error)}.ok,.bf-success{color:var(--bf-success);background:var(--bf-card);border-color:var(--bf-success)}\n'
    css += 'html{background-color:var(--bf-bg);color-scheme:dark}html[data-theme="light"]{color-scheme:light}body{font-family:var(--bf-font-ui)}.serif{font-family:var(--bf-font-display)}.card{border-radius:var(--bf-radius-card)}\n'
    return css

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for target in ['cloud/public/semantic-tokens.css','sales/assets/semantic-tokens.css','app/web-modern/src/semantic-tokens.css','shared/canvas/semantic-tokens.css']:
        p=ROOT/target
        if args.check:
            if not p.exists() or p.read_text()!=render(): raise SystemExit('Token drift: '+target)
        else: p.write_text(render())
    print('Shared UI semantic tokens match source.')
if __name__=='__main__':main()
