"""Regression: /api/chat provider overrides must be request-local.

The old implementation mutated the shared engine singleton (eng.provider /
eng.model / eng.api_key) and restored it in `finally`. Two concurrent chats
with different providers interleaved so each request executed with the
OTHER request's provider and API key (verified with threads). The fix uses
a shallow per-request copy; this test widens the race window with sleeps and
asserts each response was generated by its own provider with its own key.
"""

import threading
import time


def test_concurrent_provider_overrides_stay_isolated(client, monkeypatch):
    monkeypatch.setenv("GROQ_API_KEY", "gsk_test_key_aaaaaaaaa")
    monkeypatch.setenv("GEMINI_API_KEY", "aiza_test_key_bbbbbb")

    from engines.ai_engine import AIEngine

    def fake_groq(self, prompt, system_prompt, max_tokens):
        time.sleep(0.25)  # widen the window the old code raced in
        return f"groq|{self.provider}|{self.api_key}"

    def fake_gemini(self, prompt, system_prompt, max_tokens):
        time.sleep(0.25)
        return f"gemini|{self.provider}|{self.api_key}"

    monkeypatch.setattr(AIEngine, "_call_groq_api", fake_groq)
    monkeypatch.setattr(AIEngine, "_call_gemini_api", fake_gemini)

    results = {}

    def call(tag, provider):
        r = client.post("/api/chat", json={"message": "race test message", "provider": provider})
        assert r.status_code == 200, r.text
        results[tag] = r.json()["brandforge_response"]

    t1 = threading.Thread(target=call, args=("a", "groq"))
    t2 = threading.Thread(target=call, args=("b", "gemini"))
    t1.start()
    time.sleep(0.05)  # ensure overlap: A is mid-call when B switches provider
    t2.start()
    t1.join(timeout=15)
    t2.join(timeout=15)

    assert results["a"] == "groq|groq|gsk_test_key_aaaaaaaaa", results
    assert results["b"] == "gemini|gemini|aiza_test_key_bbbbbb", results

    # The shared singleton must be untouched by the overrides
    import server
    eng, _, _, _ = server.get_core()
    assert eng.provider == "offline"


def test_artifact_responses_are_sandboxed(client):
    """Generated HTML/SVG deliverables must ship a locked-down CSP
    (no scripts, no same-origin access) — defense in depth on top of
    input sanitization."""
    r = client.post("/api/swarm/run", json={
        "campaign_name": "csp probe", "product_name": "CSPTest",
        "industry": "x", "target_audience": "y", "key_benefits": "z"})
    assert r.status_code == 200
    name = r.json()["campaign_name"]

    svg = client.get(f"/api/campaigns/{name}/files/hero_banner.svg")
    assert svg.status_code == 200
    csp = svg.headers.get("content-security-policy", "")
    assert "sandbox" in csp and "default-src 'none'" in csp

    html = client.get(f"/api/campaigns/{name}/files/ad_card.html")
    assert "sandbox" in html.headers.get("content-security-policy", "")

    # ...while the dashboard itself keeps the standard CSP
    health = client.get("/health")
    assert "default-src 'self'" in health.headers.get("content-security-policy", "")
